export interface Formulario {
  id: string
  title: string
  subtitle?: string
  description: string
  details?: string[]
  pages?: string
  fileSize?: string
  price?: number
  tier: 1 | 2 | 3 | 4 | 5 | 6 | 7
  category: "protocolo" | "formulario" | "guia" | "lamina" | "compendio" | "apostila"
  coverColor: string
  featured?: boolean
  hotmartUrl?: string
}

export const tiers = [
  {
    id: 1,
    name: "Máxima Complexidade",
    subtitle: "40–200+ páginas",
    description: "Integrados, multidisciplinares. Síntese de múltiplos domínios clínicos.",
    color: "#C8102E",
    icon: "🔴",
  },
  {
    id: 2,
    name: "Alta Complexidade",
    subtitle: "20–50 páginas",
    description: "Especializados em uma disciplina. Conhecimento profundo.",
    color: "#B8783D",
    icon: "🟠",
  },
  {
    id: 3,
    name: "Complexidade Média",
    subtitle: "10–25 páginas",
    description: "Bem estruturados. Um diagnóstico ou tecnologia específica.",
    color: "#FF9800",
    icon: "🟡",
  },
  {
    id: 4,
    name: "Referência Rápida",
    subtitle: "2–10 páginas",
    description: "Guias, lâminas, compêndios. Consulta objetiva.",
    color: "#0096B4",
    icon: "🟢",
  },
  {
    id: 5,
    name: "Sínteses de Pesquisa",
    subtitle: "10–20 páginas",
    description: "Revisões de literatura com evidências. Complementam protocolos.",
    color: "#0066CC",
    icon: "🔵",
  },
  {
    id: 6,
    name: "Lâminas Técnicas",
    subtitle: "Dupla-face A4H",
    description: "Apresentações para consultório. Frente clínica + verso farmacotécnico.",
    color: "#4a5568",
    icon: "⬜",
  },
  {
    id: 7,
    name: "Formulários Integrados",
    subtitle: "Sistemas completos",
    description: "Formulários magistrais com protocolos e fluxos integrados.",
    color: "#8B4513",
    icon: "📦",
  },
]

export const formularios: Formulario[] = [
  // TIER 1 — MÁXIMA COMPLEXIDADE
  {
    id: "peptideos-2026",
    title: "Formulário Integrado Peptídeos 2026",
    subtitle: "O mais completo do mercado brasileiro",
    description: "60+ fórmulas magistrais com concentrações exatas, pH, modos de uso. Cobertura completa de peptídeos regenerativos para dermatologia avançada.",
    details: [
      "Ativos: GHKCu, EGF, bFGF, IGF-1, VEGFr, Colágeno I/III, PDRN, Exossomos",
      "Indicações: Envelhecimento, Cicatrização, Pós-laser, Queloide, Alopecia",
      "Público: Dermatologistas regenerativistas, Pesquisadores, Consultores sênior",
    ],
    pages: "150p",
    fileSize: "2.6 MB",
    price: 497,
    tier: 1,
    category: "formulario",
    coverColor: "#C8102E",
    featured: true,
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "peelings-exclusivos",
    title: "Protocolo Peelings Exclusivos",
    subtitle: "18 sequências validadas em clínica",
    description: "Protocolos completos para Melasma, Acne, Anti-Aging e Pós-Laser. Cada sequência com cronograma, concentrações e cuidados pós.",
    details: [
      "Ativos: ATA GREEN™, TCA 15–35%, Mandélico, Retinóico, Salicílico, Glicólico",
      "Protocolos: 18 sequências (Melasma 6, Acne 4, Anti-Aging 5, Pós-Laser 3)",
      "Público: Dermatologistas procedurais, Clínicas estéticas",
    ],
    pages: "45p",
    fileSize: "42 KB",
    price: 347,
    tier: 1,
    category: "protocolo",
    coverColor: "#C8102E",
    featured: true,
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "guia-terapeutico",
    title: "Guia Terapêutico Dermatológico Magistral",
    subtitle: "42 diagnósticos mapeados",
    description: "200+ prescrições com compatibilidades confirmadas. O guia definitivo para profissionais magistrais e consultores.",
    details: [
      "Diagnósticos: 42 condições dermatológicas mapeadas",
      "Fórmulas: 200+ prescrições com compatibilidades confirmadas",
      "Público: Farmacêuticos magistrais sênior, Consultores, Formuladores",
    ],
    pages: "80p",
    fileSize: "43 KB",
    price: 397,
    tier: 1,
    category: "guia",
    coverColor: "#C8102E",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },

  // TIER 2 — ALTA COMPLEXIDADE
  {
    id: "melasma-integrado",
    title: "Protocolo Melasma Integrado",
    subtitle: "45 fórmulas + 6 algoritmos",
    description: "Algoritmos de 4/8/12 semanas com integração Laser + Microagulhamento. O protocolo mais completo para melasma resistente.",
    details: [
      "45 fórmulas validadas em clínica",
      "6 algoritmos temporais (4/8/12 semanas)",
      "Integração: Laser, Microagulhamento, Tópicos",
    ],
    pages: "25p",
    price: 197,
    tier: 2,
    category: "protocolo",
    coverColor: "#B8783D",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "rosacea-graus",
    title: "Protocolo Rosácea Graus I–III",
    subtitle: "18 prescrições graduadas",
    description: "Abordagem por grau de severidade com Azelaico 15–20% e Niacinamida 4–5%. Protocolos para todos os fenótipos.",
    details: [
      "18 prescrições organizadas por grau",
      "Azelaico 15–20% + Niacinamida 4–5%",
      "Cobertura: Eritematotelangiectásica, Papulopustulosa, Fimatosa",
    ],
    pages: "20p",
    price: 147,
    tier: 2,
    category: "protocolo",
    coverColor: "#B8783D",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "fatores-crescimento",
    title: "Formulário Fatores de Crescimento",
    subtitle: "50+ prescrições regenerativas",
    description: "Cobertura completa de VEGF-r, IGF-1, EGF, bFGF, TGF-β, FGF-2, PDRN. Para regeneração tecidual avançada.",
    details: [
      "50+ prescrições com concentrações validadas",
      "Ativos: VEGF-r, IGF-1, EGF, bFGF, TGF-β, FGF-2, PDRN",
      "Aplicações: Cicatrização, Anti-aging, Pós-procedimento",
    ],
    pages: "35p",
    price: 197,
    tier: 2,
    category: "formulario",
    coverColor: "#B8783D",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "incompatibilidades",
    title: "Incompatibilidades & Erros Farmacotécnicos",
    subtitle: "80+ pares incompatíveis",
    description: "Matriz interativa com 3 níveis de criticidade. Evite erros de formulação e retrabalho de bancada.",
    details: [
      "80+ pares incompatíveis documentados",
      "3 níveis de criticidade (Crítico, Moderado, Leve)",
      "Matriz interativa para consulta rápida",
    ],
    pages: "15p",
    price: 97,
    tier: 2,
    category: "guia",
    coverColor: "#B8783D",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },

  // TIER 3 — COMPLEXIDADE MÉDIA
  {
    id: "periorbital",
    title: "Periorbital, Pescoço & Colo",
    description: "Protocolos de 12 semanas para rugas, flacidez e manchas em áreas delicadas.",
    pages: "15p",
    price: 97,
    tier: 3,
    category: "protocolo",
    coverColor: "#FF9800",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "estrias",
    title: "Estrias Atróficas Recentes",
    description: "Tripla terapia: Laser + Microagulhamento + Tópico para máxima eficácia.",
    pages: "12p",
    price: 97,
    tier: 3,
    category: "protocolo",
    coverColor: "#FF9800",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "acne-tripla",
    title: "Acne – Tripla Combinação",
    description: "Azelaico 15–20% + Niacinamida 4–5% + Salicílico 2–5%. Protocolo sinérgico.",
    pages: "10p",
    price: 77,
    tier: 3,
    category: "protocolo",
    coverColor: "#FF9800",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "acne-rosacea-foliculoses",
    title: "Acne, Rosácea & Foliculoses",
    description: "5 algoritmos e 20+ prescrições para condições inflamatórias faciais.",
    pages: "18p",
    price: 97,
    tier: 3,
    category: "protocolo",
    coverColor: "#FF9800",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "psoriase-eczemas",
    title: "Psoríase & Eczemas",
    description: "Corticosteroides, Queratolíticos e Imunomoduladores em protocolos graduados.",
    pages: "15p",
    price: 97,
    tier: 3,
    category: "protocolo",
    coverColor: "#FF9800",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "discromias",
    title: "Discromias",
    description: "Melasma, Sardas, Lentigos e Vitiligo. Abordagem por tipo de hipercromia.",
    pages: "20p",
    price: 97,
    tier: 3,
    category: "protocolo",
    coverColor: "#FF9800",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "alopecias",
    title: "Alopecias & Tricoses",
    description: "Alopecia androgênica, areata e telógena. Protocolos tópicos e mesoterapia.",
    pages: "18p",
    price: 97,
    tier: 3,
    category: "protocolo",
    coverColor: "#FF9800",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "onicoses",
    title: "Onicoses & Onicomicoses",
    description: "Antifúngicos e Queratolíticos em protocolos de 8–12 semanas.",
    pages: "12p",
    price: 77,
    tier: 3,
    category: "protocolo",
    coverColor: "#FF9800",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "micoses",
    title: "Micoses Superficiais",
    description: "Dermatofitoses, Candidoses e Pitiriásis versicolor. Protocolos tópicos.",
    pages: "10p",
    price: 67,
    tier: 3,
    category: "protocolo",
    coverColor: "#FF9800",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },

  // TIER 4 — REFERÊNCIA RÁPIDA
  {
    id: "apostila-veiculos-2026",
    title: "Apostila Veículos 2026",
    subtitle: "51 páginas · 15 capítulos",
    description: "Compêndio completo com 20 bases validadas. O guia definitivo de veículos magistrais.",
    pages: "51p",
    price: 127,
    tier: 4,
    category: "apostila",
    coverColor: "#0096B4",
    featured: true,
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "compendio-bases",
    title: "Compêndio Bases Cosméticas",
    description: "20 bases validadas com propriedades físico-químicas detalhadas.",
    pages: "15p",
    price: 67,
    tier: 4,
    category: "compendio",
    coverColor: "#0096B4",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "tecnologia-veiculos",
    title: "Tecnologia de Veículos",
    description: "Emulsificação, Estabilidade e Reologia. Fundamentos técnicos.",
    pages: "12p",
    price: 57,
    tier: 4,
    category: "guia",
    coverColor: "#0096B4",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "veiculos-magistrais",
    title: "Veículos Magistrais",
    description: "Seleção rápida com INCI e indicações por tipo de pele.",
    pages: "8p",
    price: 47,
    tier: 4,
    category: "guia",
    coverColor: "#0096B4",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "fundamentos-veiculos",
    title: "Fundamentos de Veículos",
    description: "Farmacocinética, pH e Permeação cutânea. Base teórica essencial.",
    pages: "10p",
    price: 47,
    tier: 4,
    category: "guia",
    coverColor: "#0096B4",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },

  // TIER 5 — SÍNTESES DE PESQUISA
  {
    id: "fisiologia-peelings",
    title: "Fisiologia de Peelings",
    description: "Revisão de literatura sobre mecanismos de ação e regeneração epidérmica.",
    pages: "15p",
    price: 67,
    tier: 5,
    category: "guia",
    coverColor: "#0066CC",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "ativos-clareadores",
    title: "Ativos Clareadores",
    description: "Evidências científicas de eficácia e segurança dos principais despigmentantes.",
    pages: "18p",
    price: 77,
    tier: 5,
    category: "guia",
    coverColor: "#0066CC",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "protocolos-peelings",
    title: "Protocolos de Peelings",
    description: "Revisão sistemática de protocolos publicados em literatura indexada.",
    pages: "20p",
    price: 87,
    tier: 5,
    category: "guia",
    coverColor: "#0066CC",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "fotobiomodulacao",
    title: "Fotobiomodulação",
    description: "LED, LLLT e mecanismos de bioestimulação. Evidências e protocolos.",
    pages: "15p",
    price: 67,
    tier: 5,
    category: "guia",
    coverColor: "#0066CC",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "pdt-fotossensibilizadores",
    title: "PDT & Fotossensibilizadores",
    description: "Terapia fotodinâmica: ALA, MAL, fotossensibilizadores e protocolos clínicos.",
    pages: "12p",
    price: 57,
    tier: 5,
    category: "guia",
    coverColor: "#0066CC",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "retinoides-peeling",
    title: "Retinoides & Peeling",
    description: "Combinação sinérgica de retinoides com peelings químicos. Evidências.",
    pages: "10p",
    price: 57,
    tier: 5,
    category: "guia",
    coverColor: "#0066CC",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },

  // TIER 6 — LÂMINAS TÉCNICAS
  {
    id: "lamina-ghkcu",
    title: "GHKCu – Pele Firme",
    description: "Lâmina dupla-face: frente clínica com indicações + verso farmacotécnico.",
    pages: "2p",
    price: 27,
    tier: 6,
    category: "lamina",
    coverColor: "#4a5568",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "lamina-botox-topico",
    title: "Botox Tópico",
    description: "Peptídeos com ação botulínica-like. Argireline, Leuphasyl, SNAP-8.",
    pages: "2p",
    price: 27,
    tier: 6,
    category: "lamina",
    coverColor: "#4a5568",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "lamina-clareamento",
    title: "Clareamento Peptídeos",
    description: "Peptídeos despigmentantes: Lumixyl, Melanostatine, Oligopeptide-68.",
    pages: "2p",
    price: 27,
    tier: 6,
    category: "lamina",
    coverColor: "#4a5568",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "lamina-regen",
    title: "Regen Pós-Procedimento",
    description: "Protocolo de recuperação pós-laser, microagulhamento e peelings.",
    pages: "2p",
    price: 27,
    tier: 6,
    category: "lamina",
    coverColor: "#4a5568",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "lamina-pele-sensivel",
    title: "Pele Sensível",
    description: "Protocolos para pele reativa, rosácea e dermatite de contato.",
    pages: "2p",
    price: 27,
    tier: 6,
    category: "lamina",
    coverColor: "#4a5568",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "lamina-colageno",
    title: "Colágeno Papilar",
    description: "Estimulação de colágeno tipo I e III. Retinoides + Peptídeos.",
    pages: "2p",
    price: 27,
    tier: 6,
    category: "lamina",
    coverColor: "#4a5568",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "lamina-ghkcu-capilar",
    title: "GHKCu Capilar",
    description: "Protocolo capilar com GHKCu para alopecia e fortalecimento.",
    pages: "2p",
    price: 27,
    tier: 6,
    category: "lamina",
    coverColor: "#4a5568",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "lamina-exossomos",
    title: "Exossomos Capilar",
    description: "Exossomos e fatores de crescimento para regeneração capilar.",
    pages: "2p",
    price: 27,
    tier: 6,
    category: "lamina",
    coverColor: "#4a5568",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "lamina-pos-peeling",
    title: "Pós-Peeling D1/D7/D14",
    description: "Cronograma de cuidados pós-peeling: Dia 1, Dia 7 e Dia 14.",
    pages: "2p",
    price: 27,
    tier: 6,
    category: "lamina",
    coverColor: "#4a5568",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "lamina-acne-pih",
    title: "Acne + PIH",
    description: "Protocolo para acne ativa com hiperpigmentação pós-inflamatória.",
    pages: "2p",
    price: 27,
    tier: 6,
    category: "lamina",
    coverColor: "#4a5568",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "lamina-rejuvenescimento",
    title: "Rejuvenescimento Multi",
    description: "Protocolo multimodal: Retinoides + AHAs + Peptídeos + Antioxidantes.",
    pages: "2p",
    price: 27,
    tier: 6,
    category: "lamina",
    coverColor: "#4a5568",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "lamina-queloidectomia",
    title: "Queloidectomia",
    description: "Protocolo pós-queloidectomia com silicone e corticoides.",
    pages: "2p",
    price: 27,
    tier: 6,
    category: "lamina",
    coverColor: "#4a5568",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
  {
    id: "lamina-ghkcu-pdrn",
    title: "GHKCu + PDRN Capilar",
    description: "Combinação sinérgica para regeneração capilar intensiva.",
    pages: "2p",
    price: 27,
    tier: 6,
    category: "lamina",
    coverColor: "#4a5568",
    hotmartUrl: "https://pay.hotmart.com/A105091762I",
  },
]

export const stats = {
  totalArtefatos: "60+",
  protocolosClinicos: 27,
  laminasTecnicas: 13,
  paginasTotais: "450–500p",
}
