export type LojaTier = "T1" | "T2" | "T3" | "T4" | "T5" | "T6" | "T7"
export type LojaCategory = "formulario" | "protocolo" | "guia" | "lamina" | "compendio" | "sintese"

export interface LojaItem {
  id: string
  tier: LojaTier
  category: LojaCategory
  title: string
  subtitle: string
  description: string
  pages: string
  size?: string
  assets: string[]
  formulas?: number
  audience: string[]
  price: number
  priceOriginal?: number
  featured?: boolean
  badge?: string
  hotmartId?: string
}

export const TIER_LABELS: Record<LojaTier, { label: string; color: string; accent: string; desc: string }> = {
  T1: {
    label: "Máxima Complexidade",
    color: "#7c1d1d",
    accent: "#dc2626",
    desc: "Integrados, multidisciplinares · 40–200+ páginas",
  },
  T2: {
    label: "Alta Complexidade",
    color: "#9a3412",
    accent: "#ea580c",
    desc: "Especializados · 20–50 páginas",
  },
  T3: {
    label: "Complexidade Média",
    color: "#854d0e",
    accent: "#ca8a04",
    desc: "Diagnóstico específico · 10–25 páginas",
  },
  T4: {
    label: "Referência Rápida",
    color: "#14532d",
    accent: "#16a34a",
    desc: "Guias e compêndios · 2–10 páginas",
  },
  T5: {
    label: "Pesquisa Científica",
    color: "#1e3a8a",
    accent: "#2563eb",
    desc: "Revisões peer-reviewed · 10–20 páginas",
  },
  T6: {
    label: "Lâminas Técnicas",
    color: "#374151",
    accent: "#6b7280",
    desc: "Dupla-face A4H · 13 lâminas",
  },
  T7: {
    label: "Formulários Integrados",
    color: "#581c87",
    accent: "#9333ea",
    desc: "Coleções de prescrições · 40–150 fórmulas",
  },
}

export const CATEGORY_LABELS: Record<LojaCategory, string> = {
  formulario: "Formulário",
  protocolo: "Protocolo",
  guia: "Guia Técnico",
  lamina: "Lâmina",
  compendio: "Compêndio",
  sintese: "Síntese",
}

export const LOJA_ITEMS: LojaItem[] = [
  // TIER 1 — MÁXIMA COMPLEXIDADE
  {
    id: "peptideos-2026",
    tier: "T1",
    category: "formulario",
    title: "Formulário Integrado Peptídeos 2026",
    subtitle: "60+ fórmulas magistrais com GHKCu, EGF, bFGF, IGF-1, VEGFr, Colágeno, PDRN, Exo",
    description:
      "O compêndio mais completo do Brasil sobre peptídeos e fatores de crescimento para dermatologia regenerativa. % exata, pH validado, modos de aplicação, indicações clínicas por patologia.",
    pages: "150 páginas",
    size: "2,6 MB",
    assets: ["GHK-Cu", "EGF", "bFGF", "IGF-1", "VEGFr", "Colágeno Peptídeos", "PDRN", "Exossomos"],
    formulas: 60,
    audience: ["Dermatologistas regenerativistas", "Pesquisadores", "Farmacêuticos magistrais"],
    price: 497,
    priceOriginal: 697,
    featured: true,
    badge: "Mais Vendido",
  },
  {
    id: "peelings-exclusivos",
    tier: "T1",
    category: "protocolo",
    title: "Protocolo Peelings Exclusivos",
    subtitle: "18 sequências clínicas com ATA GREEN™, TCA 15–35%, Mandélico, Retinóico, Salicílico",
    description:
      "Sequências completas para melasma (6), acne (4), anti-aging (5) e pós-laser (3). Pré, procedimento, pós e sinais de alerta em cada sequência.",
    pages: "45 páginas",
    size: "42 KB",
    assets: ["ATA GREEN™", "TCA 15–35%", "Mandélico", "Retinóico", "Salicílico"],
    audience: ["Dermatologistas procedurais", "Clínicas estéticas"],
    price: 297,
    priceOriginal: 397,
    badge: "Essencial",
  },
  {
    id: "guia-terapeutico",
    tier: "T1",
    category: "guia",
    title: "Guia Terapêutico Dermatológico Magistral",
    subtitle: "200+ prescrições para 42 condições dermatológicas",
    description:
      "Compêndio clínico-científico com diagnósticos, compatibilidades, incompatibilidades e protocolos validados para o dia a dia da farmácia magistral sênior.",
    pages: "43 KB estruturado",
    assets: ["42 diagnósticos", "200+ prescrições", "Matriz de compatibilidade"],
    audience: ["Farmacêuticos magistrais sênior", "Consultores técnicos"],
    price: 397,
    priceOriginal: 547,
  },

  // TIER 2 — ALTA COMPLEXIDADE
  {
    id: "melasma-integrado",
    tier: "T2",
    category: "protocolo",
    title: "Protocolo Melasma Integrado",
    subtitle: "45 fórmulas · 6 algoritmos de 4/8/12 semanas · Laser + microagulhamento",
    description:
      "Abordagem integrada do melasma refratário: topicamente, procedimentos e manutenção domiciliar. Todos os algoritmos com referência peer-reviewed.",
    pages: "25 páginas",
    assets: ["Ácido Tranexâmico", "Hidroquinona 4–8%", "Cisteamina", "Ácido Azelaico"],
    formulas: 45,
    audience: ["Dermatologistas estéticos", "Clínicas especializadas"],
    price: 247,
  },
  {
    id: "rosacea-i-iii",
    tier: "T2",
    category: "protocolo",
    title: "Protocolo Rosácea Graus I–III",
    subtitle: "18 prescrições com Azelaico 15–20%, Niacinamida 4–5%, Brimonidina tópica",
    description:
      "Estratégia por grau de acometimento, com manejo vascular, anti-inflamatório e barreira cutânea.",
    pages: "20 páginas",
    assets: ["Azelaico 15–20%", "Niacinamida 4–5%", "Ivermectina", "Brimonidina"],
    formulas: 18,
    audience: ["Dermatologistas clínicos", "Farmacêuticos magistrais"],
    price: 197,
  },
  {
    id: "fatores-crescimento",
    tier: "T2",
    category: "formulario",
    title: "Formulário Fatores de Crescimento",
    subtitle: "50+ prescrições com VEGF-r, IGF-1, EGF, bFGF, TGF-β, FGF-2, PDRN",
    description:
      "Prescrições magistrais com fatores de crescimento recombinantes, compatibilidades, veículos e estabilidade para regeneração tecidual e cicatrização.",
    pages: "35 páginas",
    assets: ["VEGF-r", "IGF-1", "EGF", "bFGF", "TGF-β", "FGF-2", "PDRN"],
    formulas: 50,
    audience: ["Farmacêuticos magistrais", "Clínicas com laser/procedimento"],
    price: 347,
    priceOriginal: 447,
  },
  {
    id: "incompatibilidades",
    tier: "T2",
    category: "guia",
    title: "Incompatibilidades & Erros Farmacotécnicos",
    subtitle: "Matriz interativa com 80+ pares incompatíveis em 3 níveis de criticidade",
    description:
      "Ferramenta de consulta rápida com os erros mais frequentes do balcão magistral e como corrigi-los antes que virem ação sanitária ou retrabalho.",
    pages: "15 KB interativo",
    assets: ["80+ pares críticos", "3 níveis de alerta", "Matriz visual"],
    audience: ["Farmacêuticos magistrais", "Auditores técnicos"],
    price: 167,
  },

  // TIER 3 — COMPLEXIDADE MÉDIA
  {
    id: "periorbital-pescoco",
    tier: "T3",
    category: "protocolo",
    title: "Protocolo Periorbital, Pescoço & Colo",
    subtitle: "Abordagem integrada de áreas delicadas",
    description: "Peptídeos, retinoides de baixa irritação e estratégias de firmeza cutânea.",
    pages: "15 páginas",
    assets: ["Peptídeos", "Bakuchiol", "Retinaldeído", "Colágeno"],
    audience: ["Dermatologistas estéticos"],
    price: 127,
  },
  {
    id: "estrias-atroficas",
    tier: "T3",
    category: "protocolo",
    title: "Protocolo Estrias Atróficas Recentes",
    subtitle: "Microagulhamento + ativos regenerativos",
    description:
      "Combinação de tecnologias físicas e topicamente com retinoides, peptídeos e fatores de crescimento.",
    pages: "18 páginas",
    assets: ["Tretinoína", "Peptídeos de cobre", "Ácido hialurônico"],
    audience: ["Clínicas com laser", "Dermatologistas procedurais"],
    price: 147,
  },
  {
    id: "acne-tripla",
    tier: "T3",
    category: "protocolo",
    title: "Acne — Tripla Combinação",
    subtitle: "Azelaico + Niacinamida + Salicílico",
    description: "Protocolo validado por estudos clínicos, pronto para prescrição.",
    pages: "5 páginas",
    assets: ["Azelaico", "Niacinamida", "Salicílico"],
    formulas: 6,
    audience: ["Dermatologistas clínicos"],
    price: 67,
  },
  {
    id: "acne-rosacea-folic",
    tier: "T3",
    category: "protocolo",
    title: "Acne, Rosácea & Foliculoses",
    subtitle: "5 algoritmos · 20+ prescrições",
    description: "Diferencial diagnóstico e condutas paralelas para os três quadros.",
    pages: "4 páginas",
    assets: ["Isotretinoína tópica", "Clindamicina", "Metronidazol"],
    audience: ["Dermatologistas clínicos"],
    price: 57,
  },
  {
    id: "psoriase-eczemas",
    tier: "T3",
    category: "protocolo",
    title: "Psoríase & Eczemas",
    subtitle: "Corticoides, calcipotriol, inibidores de calcineurina",
    description: "Escada terapêutica com segurança em uso prolongado.",
    pages: "3 páginas",
    assets: ["Calcipotriol", "Tacrolimus", "Corticoides potentes"],
    audience: ["Dermatologistas clínicos"],
    price: 47,
  },
  {
    id: "discromias",
    tier: "T3",
    category: "protocolo",
    title: "Discromias",
    subtitle: "Melasma, sardas, lentigos, vitiligo",
    description: "Abordagem por etiologia da hipercromia ou hipocromia.",
    pages: "3 páginas",
    assets: ["Hidroquinona", "Kligman", "Ácido tranexâmico"],
    audience: ["Dermatologistas clínicos"],
    price: 47,
  },
  {
    id: "alopecias",
    tier: "T3",
    category: "protocolo",
    title: "Alopecias & Tricoses",
    subtitle: "Minoxidil, finasterida, PRP e peptídeos",
    description: "Do padrão androgenética à alopecia areata, passando por eflúvios.",
    pages: "3 páginas",
    assets: ["Minoxidil", "Finasterida tópica", "GHK-Cu capilar"],
    audience: ["Tricologistas", "Dermatologistas"],
    price: 47,
  },
  {
    id: "onicoses",
    tier: "T3",
    category: "protocolo",
    title: "Onicoses & Onicomicoses",
    subtitle: "Protocolos de 8–12 semanas",
    description: "Antifúngicos tópicos, queratolíticos e manejo sistêmico complementar.",
    pages: "3 páginas",
    assets: ["Ciclopirox", "Amorolfina", "Ureia 40%"],
    audience: ["Dermatologistas clínicos"],
    price: 47,
  },
  {
    id: "micoses",
    tier: "T3",
    category: "protocolo",
    title: "Micoses Superficiais",
    subtitle: "Tinhas, pitiríase, candidíases",
    description: "Diferencial diagnóstico e tratamento tópico vs sistêmico.",
    pages: "3 páginas",
    assets: ["Cetoconazol", "Terbinafina", "Miconazol"],
    audience: ["Dermatologistas clínicos"],
    price: 47,
  },

  // TIER 4 — REFERÊNCIA RÁPIDA
  {
    id: "apostila-veiculos-2026",
    tier: "T4",
    category: "compendio",
    title: "Apostila Veículos Dermatológicos 2026",
    subtitle: "15 capítulos + compêndio de 20 bases validadas",
    description:
      "Referência técnica para escolha racional do veículo, com farmacocinética, permeação, estabilidade e reologia.",
    pages: "51 páginas",
    assets: ["15 capítulos", "20 bases", "INCI + nome comercial"],
    audience: ["Farmacêuticos magistrais", "Formadores", "Estudantes pós-graduação"],
    price: 197,
    priceOriginal: 267,
    featured: true,
    badge: "Novidade",
  },
  {
    id: "compendio-bases",
    tier: "T4",
    category: "compendio",
    title: "Compêndio Bases Cosméticas",
    subtitle: "20 bases validadas com INCI e nome comercial",
    description: "Guia de seleção rápida com pH, viscosidade, compatibilidade e aplicações.",
    pages: "Compêndio tabulado",
    assets: ["20 bases", "pH/viscosidade", "Compatibilidade"],
    audience: ["Farmacêuticos magistrais"],
    price: 97,
  },
  {
    id: "tecnologia-veiculos",
    tier: "T4",
    category: "guia",
    title: "Tecnologia de Veículos",
    subtitle: "Emulsificação, estabilidade, reologia",
    description: "Princípios físico-químicos aplicados ao balcão.",
    pages: "Guia técnico",
    assets: ["Emulsificação", "Estabilidade", "Reologia"],
    audience: ["Farmacêuticos magistrais", "P&D cosmético"],
    price: 87,
  },

  // TIER 5 — SÍNTESES DE PESQUISA
  {
    id: "fisiologia-peelings",
    tier: "T5",
    category: "sintese",
    title: "Fisiologia de Peelings",
    subtitle: "Revisão peer-reviewed",
    description: "Mecanismos de ação, profundidade, wound healing e resposta inflamatória.",
    pages: "Síntese científica",
    assets: ["Peer-reviewed", "DOIs indexados"],
    audience: ["Pesquisadores", "Dermatologistas procedurais"],
    price: 77,
  },
  {
    id: "ativos-clareadores",
    tier: "T5",
    category: "sintese",
    title: "Ativos Clareadores",
    subtitle: "Revisão comparativa de eficácia",
    description: "Hidroquinona, cisteamina, ácido tranexâmico, ácido kójico e novos ativos.",
    pages: "Síntese científica",
    assets: ["Estudos randomizados", "Meta-análises"],
    audience: ["Dermatologistas clínicos", "Pesquisadores"],
    price: 77,
  },
  {
    id: "fotobiomodulacao",
    tier: "T5",
    category: "sintese",
    title: "Fotobiomodulação",
    subtitle: "LED vermelho, âmbar, azul · mecanismos moleculares",
    description: "Evidências clínicas e protocolos para dermatologia e tricologia.",
    pages: "Síntese científica",
    assets: ["LLLT", "LEDT", "Comprimentos de onda"],
    audience: ["Dermatologistas", "Fisioterapeutas dermatofuncionais"],
    price: 77,
  },
  {
    id: "pdt-fotossens",
    tier: "T5",
    category: "sintese",
    title: "PDT & Fotossensibilizadores",
    subtitle: "Terapia fotodinâmica em dermato-oncologia e estética",
    description: "ALA, MAL, protocolos e evidências clínicas.",
    pages: "Síntese científica",
    assets: ["ALA", "MAL", "Protocolos PDT"],
    audience: ["Dermatologistas oncológicos", "Estética avançada"],
    price: 77,
  },
  {
    id: "retinoides-peeling",
    tier: "T5",
    category: "sintese",
    title: "Retinoides & Peeling",
    subtitle: "Sinergia, protocolos e segurança",
    description: "Tretinoína, adapaleno, retinaldeído e bakuchiol em protocolos integrados.",
    pages: "Síntese científica",
    assets: ["Tretinoína", "Adapaleno", "Retinaldeído", "Bakuchiol"],
    audience: ["Dermatologistas clínicos"],
    price: 77,
  },

  // TIER 6 — LÂMINAS TÉCNICAS
  {
    id: "laminas-pack",
    tier: "T6",
    category: "lamina",
    title: "Pack 13 Lâminas Técnicas Dupla-Face A4H",
    subtitle: "Apresentações para consultório · Frente clínica + verso técnico",
    description:
      "Kit completo: GHKCu Pele Firme, Botox Tópico, Clareamento Peptídeos, Regen Pós-Proc, Pele Sensível, Colágeno Papilar, GHKCu Capilar, Exossomos Capilar, Pós-Peeling D1/D7/D14, Acne+PIH, Rejuvenescimento Multimodal, Queloidectomia, GHKCu+PDRN Capilar.",
    pages: "26 páginas (PDF unificado)",
    assets: ["13 lâminas", "Frente clínica", "Verso técnico"],
    audience: ["Dermatologistas estéticos", "Consultórios"],
    price: 297,
    priceOriginal: 447,
    featured: true,
    badge: "Kit Completo",
  },

  // TIER 7 — FORMULÁRIOS INTEGRADOS
  {
    id: "formulario-melasma",
    tier: "T7",
    category: "formulario",
    title: "Formulário Melasma 2026",
    subtitle: "45 fórmulas magistrais com algoritmos",
    description: "Coleção organizada por gravidade e fotótipo.",
    pages: "Formulário integrado",
    assets: ["45 fórmulas", "Algoritmos 4/8/12 semanas"],
    formulas: 45,
    audience: ["Farmacêuticos magistrais", "Dermatologistas"],
    price: 197,
  },
  {
    id: "formulario-clareadores",
    tier: "T7",
    category: "formulario",
    title: "Formulário Clareadores & Antioxidantes",
    subtitle: "30+ fórmulas com vitamina C, E, ferúlico e niacinamida",
    description: "Rotina completa AM/PM para manchas e envelhecimento.",
    pages: "Formulário integrado",
    assets: ["Vit. C", "Vit. E", "Ácido Ferúlico", "Niacinamida"],
    formulas: 30,
    audience: ["Farmacêuticos magistrais"],
    price: 177,
  },
  {
    id: "formulario-bases",
    tier: "T7",
    category: "formulario",
    title: "Formulário Bases Dermatológicas",
    subtitle: "20 fórmulas de bases validadas",
    description: "Cremes, loções, géis, pomadas e hidrogéis para uso magistral.",
    pages: "Formulário integrado",
    assets: ["20 bases", "pH/viscosidade", "Estabilidade"],
    formulas: 20,
    audience: ["Farmacêuticos magistrais"],
    price: 147,
  },
]

export const LOJA_STATS = {
  totalItems: "60+",
  protocolos: 27,
  laminas: 13,
  formularios: 8,
  guias: 7,
  sinteses: 6,
  suporte: 5,
  paginas: "450–500",
}
